# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  maven-gradle-plugin:
    type: maven-repository
    url: https://plugins.gradle.org/m2/
  maven-google:
    type: maven-repository
    url: https://dl.google.com/dl/android/maven2/
  maven-apache:
    type: maven-repository
    url: https://repo.maven.apache.org/maven2/
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "06:00"
      timezone: Asia/Taipei
      
  - package-ecosystem: "gradle"
    directory: "/"
    registries:
      - maven-gradle-plugin
      - maven-google
      - maven-apache
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "06:00"
      timezone: Asia/Taipei
    reviewers:
      - "kevinguitar"
    ignore:
      # https://www.reddit.com/r/androiddev/comments/1csjwne/lifecycle_280_only_compatible_with_compose_17/
      - dependency-name: "androidx.lifecycle:lifecycle-runtime-compose"
    groups:
      kotlin-and-compose-compiler:
        patterns:
          - "org.jetbrains.kotlin:*"
          - "org.jetbrains.kotlin.*"
          - "com.google.devtools.ksp"
      androidx:
        patterns:
          - "androidx.*"
      google-play-services:
        patterns:
          - "com.google.android.gms:*"
          - "com.google.android.play:*"
