name: Android CI

on:
  pull_request:

# Cancel any current or previous job from the same PR
concurrency:
  group: android-ci-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: Configure JDK
        uses: actions/setup-java@v6
        with:
          java-version-file: .github/workflows/.java-version
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          # Only save Gradle User Home state for builds on the 'main' branch.
          # Builds on other branches will only read existing entries from the cache.
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
          # Don't reuse cache entries from any other Job.
          gradle-home-cache-strict-match: true
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      # https://github.com/orgs/community/discussions/26351#discussioncomment-3251595
      - name: Free Disk Space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          images=$(docker images -q)
          if [[ -n "$images" ]]; then
          docker rmi $images
          fi
          df -h

      # https://www.droidcon.com/2023/04/04/securely-create-android-release-using-github-actions/
      - name: Decode Keystore and Google Service file
        env:
          ENCODED_KEYSTORE: ${{ secrets.KEYSTORE_FILE }}
          ENCODED_GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          ENCODED_INSIDER_GOOGLE_SERVICES_JSON: ${{ secrets.INSIDER_GOOGLE_SERVICES_JSON }}
        run: |
          echo $ENCODED_KEYSTORE | base64 -d > ./BudgetKey
          echo $ENCODED_GOOGLE_SERVICES_JSON | base64 -d > ./androidApp/google-services.json
          echo $ENCODED_INSIDER_GOOGLE_SERVICES_JSON | base64 -d > ./insiderApp/google-services.json

      - name: Echo Secrets
        env:
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          REVENUECAT_ANDROID_API_KEY: ${{ secrets.REVENUECAT_ANDROID_API_KEY }}
          REVENUECAT_IOS_API_KEY: ${{ secrets.REVENUECAT_IOS_API_KEY }}
        run: |
          echo KEYSTORE_PATH=./BudgetKey > ./local.properties
          echo KEYSTORE_ALIAS=$KEYSTORE_ALIAS >> ./local.properties
          echo KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD >> ./local.properties
          echo REVENUECAT_ANDROID_API_KEY=$REVENUECAT_ANDROID_API_KEY >> ./local.properties
          echo REVENUECAT_IOS_API_KEY=$REVENUECAT_IOS_API_KEY >> ./local.properties

      - name: Build with Gradle
        run: ./gradlew test testAndroid lint :androidApp:assemble :insiderApp:assemble --continue --parallel
