name: Android CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # https://github.com/actions/runner-images/issues/6709#issuecomment-1361269639
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Cache Gradle and wrapper
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # https://github.com/actions/runner-images/discussions/7188
      - name: Increase swapfile
        run: |
          sudo swapoff -a
          sudo fallocate -l 15G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo swapon --show

      # https://www.droidcon.com/2023/04/04/securely-create-android-release-using-github-actions/
      - name: Decode Keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.KEYSTORE_FILE }}
        run: echo $ENCODED_KEYSTORE | base64 -d > ./BudgetKey

      - name: Decode Google Service file
        env:
          ENCODED_GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $ENCODED_GOOGLE_SERVICES_JSON | base64 -d > ./app/google-services.json

      - name: Echo Secrets
        env:
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: |
          echo KEYSTORE_PATH=./BudgetKey > ./local.properties
          echo KEYSTORE_ALIAS=$KEYSTORE_ALIAS >> ./local.properties
          echo KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD >> ./local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-configuration-cache
