name: Publish Android app to Google Play

on:
  push:
    tags:
      - '*-android'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Configure JDK
        uses: actions/setup-java@v6
        with:
          java-version-file: .github/workflows/.java-version
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          # Only save Gradle User Home state for builds on the 'main' branch.
          # Builds on other branches will only read existing entries from the cache.
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

          # Don't reuse cache entries from any other Job.
          gradle-home-cache-strict-match: true

      - name: Decode Keystore and Google Service file
        env:
          ENCODED_KEYSTORE: ${{ secrets.KEYSTORE_FILE }}
          ENCODED_GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          ENCODED_INSIDER_GOOGLE_SERVICES_JSON: ${{ secrets.INSIDER_GOOGLE_SERVICES_JSON }}
        run: |
          echo $ENCODED_KEYSTORE | base64 -d > ./BudgetKey
          echo $ENCODED_GOOGLE_SERVICES_JSON | base64 -d > ./androidApp/google-services.json
          echo $ENCODED_INSIDER_GOOGLE_SERVICES_JSON | base64 -d > ./insiderApp/google-services.json

      - name: Echo Secrets
        env:
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          REVENUECAT_ANDROID_API_KEY: ${{ secrets.REVENUECAT_ANDROID_API_KEY }}
          REVENUECAT_IOS_API_KEY: ${{ secrets.REVENUECAT_IOS_API_KEY }}
        run: |
          echo KEYSTORE_PATH=./BudgetKey > ./local.properties
          echo KEYSTORE_ALIAS=$KEYSTORE_ALIAS >> ./local.properties
          echo KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD >> ./local.properties
          echo REVENUECAT_ANDROID_API_KEY=$REVENUECAT_ANDROID_API_KEY >> ./local.properties
          echo REVENUECAT_IOS_API_KEY=$REVENUECAT_IOS_API_KEY >> ./local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Assemble release AAB
        run: ./gradlew :androidApp:bundleRelease

      - name: Set Release Name
        run: echo "RELEASE_NAME=${REF_NAME%-android}" >> $GITHUB_ENV
        env:
          REF_NAME: ${{ github.ref_name }}

      - name: Deploy the Play Store beta channel
        uses: r0adkll/upload-google-play@v1.1.5
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.kevlina.budgetplus
          releaseFiles: androidApp/build/outputs/bundle/release/androidApp-release.aab
          mappingFile: androidApp/build/outputs/mapping/release/mapping.txt
          track: beta
          # Get the tag name from the push event
          releaseName: ${{ env.RELEASE_NAME }}
          whatsNewDirectory: distribution/whatsnew

      - name: Upload build outputs
        uses: actions/upload-artifact@v7
        with:
          name: build-outputs
          retention-days: 7
          path: androidApp/build/outputs